#pragma once

enum AttachmentID { ATTACHMENTID_NULL };
enum ReanimationID { REANIMID_NULL };

enum ParticleID { PARTICLEID_NULL };
enum ParticleSystemID { PARTICLESYSTEMID_NULL };
enum ParticleEmitterID { PARTICLEEMITTERID_NULL };

enum LawnMowerID { LAWNMOWERID_NULL };
enum GridItemID { GRIDITEMID_NULL };
enum PickupID { PICKUPID_NULL };
enum ZombieID { ZOMBIEID_NULL };
enum PlantID { PLANTID_NULL };

enum ClickCode : signed int
{
    DOUBLE_RIGHTCLICK = -2,
    RIGHTCLICK = -1,

    LEFTCLICK = 1,
    DOUBLE_LEFTCLICK = 2,

    MOUSEWHEEL_CLICK = 3
};
enum AdviceType
{
    ADVICE_NONE = -1,
    ADVICE_CLICK_ON_SUN = 0,
    ADVICE_CLICKED_ON_SUN = 1,
    ADVICE_CLICKED_ON_COIN = 2,
    ADVICE_SEED_REFRESH = 3,
    ADVICE_CANT_AFFORD_PLANT = 4,
    ADVICE_PLANT_GRAVEBUSTERS_ON_GRAVES = 5,
    ADVICE_PLANT_LILYPAD_ON_WATER = 6,
    ADVICE_PLANT_TANGLEKELP_ON_WATER = 7,
    ADVICE_PLANT_SEASHROOM_ON_WATER = 8,
    ADVICE_PLANT_POTATOE_MINE_ON_LILY = 9,
    ADVICE_PLANT_WRONG_ART_TYPE = 10,
    ADVICE_PLANT_NEED_POT = 11,
    ADVICE_PLANT_NOT_ON_GRAVE = 12,
    ADVICE_PLANT_NOT_ON_CRATER = 13,
    ADVICE_CANT_PLANT_THERE = 14,
    ADVICE_PLANT_NOT_ON_WATER = 15,
    ADVICE_PLANTING_NEEDS_GROUND = 16,
    ADVICE_BEGHOULED_DRAG_TO_MATCH_3 = 17,
    ADVICE_BEGHOULED_MATCH_3 = 18,
    ADVICE_BEGHOULED_MATCH_4 = 19,
    ADVICE_BEGHOULED_SAVE_SUN = 20,
    ADVICE_BEGHOULED_USE_CRATER_1 = 21,
    ADVICE_BEGHOULED_USE_CRATER_2 = 22,
    ADVICE_PLANT_NOT_PASSED_LINE = 23,
    ADVICE_PLANT_ONLY_ON_REPEATERS = 24,
    ADVICE_PLANT_ONLY_ON_MELONPULT = 25,
    ADVICE_PLANT_ONLY_ON_SUNFLOWER = 26,
    ADVICE_PLANT_ONLY_ON_SPIKEWEED = 27,
    ADVICE_PLANT_ONLY_ON_KERNELPULT = 28,
    ADVICE_PLANT_ONLY_ON_MAGNETSHROOM = 29,
    ADVICE_PLANT_ONLY_ON_FUMESHROOM = 30,
    ADVICE_PLANT_ONLY_ON_LILYPAD = 31,
    ADVICE_PLANT_NEEDS_REPEATER = 32,
    ADVICE_PLANT_NEEDS_MELONPULT = 33,
    ADVICE_PLANT_NEEDS_SUNFLOWER = 34,
    ADVICE_PLANT_NEEDS_SPIKEWEED = 35,
    ADVICE_PLANT_NEEDS_KERNELPULT = 36,
    ADVICE_PLANT_NEEDS_MAGNETSHROOM = 37,
    ADVICE_PLANT_NEEDS_FUMESHROOM = 38,
    ADVICE_PLANT_NEEDS_LILYPAD = 39,
    ADVICE_SLOT_MACHINE_PULL = 40,
    ADVICE_HUGE_WAVE = 41,
    ADVICE_SHOVEL_REFRESH = 42,
    ADVICE_PORTAL_RELOCATING = 43,
    ADVICE_SLOT_MACHINE_COLLECT_SUN = 44,
    ADVICE_DESTORY_POTS_TO_FINISIH_LEVEL = 45,
    ADVICE_USE_SHOVEL_ON_POTS = 46,
    ADVICE_ALMOST_THERE = 47,
    ADVICE_ZOMBIQUARIUM_CLICK_TROPHY = 48,
    ADVICE_ZOMBIQUARIUM_COLLECT_SUN = 49,
    ADVICE_ZOMBIQUARIUM_CLICK_TO_FEED,
    ADVICE_ZOMBIQUARIUM_BUY_SNORKEL,
    ADVICE_I_ZOMBIE_PLANTS_NOT_REAL,
    ADVICE_I_ZOMBIE_NOT_PASSED_LINE,
    ADVICE_I_ZOMBIE_LEFT_OF_LINE,
    ADVICE_SLOT_MACHINE_SPIN_AGAIN,
    ADVICE_I_ZOMBIE_EAT_ALL_BRAINS,
    ADVICE_PEASHOOTER_DIED,
    ADVICE_STINKY_SLEEPING,
    ADVICE_BEGHOULED_NO_MOVES,
    ADVICE_PLANT_SUNFLOWER5,
    ADVICE_PLANTING_NEED_SLEEPING,
    ADVICE_CLICK_TO_CONTINUE,
    ADVICE_SURVIVE_FLAGS,
    ADVICE_UNLOCKED_MODE,
    ADVICE_NEED_WHEELBARROW,
    NUM_ADVICE_TYPES
};
enum AchievementType
{
    ACHIEVEMENT_HOME_SECURITY,
    ACHIEVEMENT_NOBEL_PEAS_PRIZE,
    ACHIEVEMENT_BETTER_OFF_DEAD,
    ACHIEVEMENT_CHINA_SHOP,
    ACHIEVEMENT_SPUDOW,
    ACHIEVEMENT_EXPLODONATOR,
    ACHIEVEMENT_MORTICULTURALIST,
    ACHIEVEMENT_DONT_PEA_IN_POOL,
    ACHIEVEMENT_ROLL_SOME_HEADS,
    ACHIEVEMENT_GROUNDED,
    ACHIEVEMENT_ZOMBOLOGIST,
    ACHIEVEMENT_PENNY_PINCHER,
    ACHIEVEMENT_SUNNY_DAYS,
    ACHIEVEMENT_POPCORN_PARTY,
    ACHIEVEMENT_GOOD_MORNING,
    ACHIEVEMENT_NO_FUNGUS_AMONG_US,
    ACHIEVEMENT_BEYOND_THE_GRAVE,
    ACHIEVEMENT_IMMORTAL,
    ACHIEVEMENT_TOWERING_WISDOM,
    ACHIEVEMENT_MUSTACHE_MODE,
    ACHIEVEMENT_DISCO_IS_UNDEAD,
    NUM_ACHIEVEMENTS
};
enum AlmanacPage
{
    ALMANAC_PAGE_INDEX,
    ALMANAC_PAGE_PLANTS,
    ALMANAC_PAGE_ZOMBIES
};
enum AwardType
{
    AWARD_FORLEVEL,
    AWARD_CREDITS_ZOMBIENOTE,
    AWARD_HELP_ZOMBIENOTE,
    AWARD_ACHIEVEMENTONLY,
    AWARD_PRECREDITS_ZOMBIENOTE,
};
enum BackgroundType
{
    BACKGROUND_1_DAY,
    BACKGROUND_2_NIGHT,
    BACKGROUND_3_POOL,
    BACKGROUND_4_FOG,
    BACKGROUND_5_ROOF,
    BACKGROUND_6_BOSS,
    BACKGROUND_MUSHROOM_GARDEN,
    BACKGROUND_GREENHOUSE,
    BACKGROUND_ZOMBIQUARIUM,
    BACKGROUND_TREEOFWISDOM
};
enum GameResult
{
    GAMERESULT_NONE = 0,
    GAMERESULT_WON = 1,
    GAMERESULT_LOST = 2,
    GAMERESULT_RESTART = 3,
    GAMERESULT_QUIT = 4,
    GAMERESULT_QUIT_APP = 5,
    GAMERESULT_CHEAT = 6
};
enum BossPart
{
    BOSS_PART_BACK_LEG = 0,
    BOSS_PART_FRONT_LEG = 1,
    BOSS_PART_MAIN = 2,
    BOSS_PART_BACK_ARM = 3,
    BOSS_PART_FIREBALL = 4
};
enum ChallengePage
{
    CHALLENGE_PAGE_CHALLENGE,
    CHALLENGE_PAGE_PUZZLE,
    CHALLENGE_PAGE_SURVIVAL,
    CHALLENGE_PAGE_LIMBO,
    MAX_CHALLENGE_PAGES
};
enum ChallengeState
{
    STATECHALLENGE_NORMAL,
    STATECHALLENGE_BEGHOULED_MOVING,
    STATECHALLENGE_BEGHOULED_FALLING,
    STATECHALLENGE_BEGHOULED_NO_MATCHES,
    STATECHALLENGE_SLOT_MACHINE_ROLLING,
    STATECHALLENGE_STORM_FLASH_1,
    STATECHALLENGE_STORM_FLASH_2,
    STATECHALLENGE_STORM_FLASH_3,
    STATECHALLENGE_ZEN_FADING,
    STATECHALLENGE_SCARY_POTTER_MALLETING,
    STATECHALLENGE_LAST_STAND_ONSLAUGHT,
    STATECHALLENGE_TREE_JUST_GREW,
    STATECHALLENGE_TREE_GIVE_WISDOM,
    STATECHALLENGE_TREE_WAITING_TO_BABBLE,
    STATECHALLENGE_TREE_BABBLING
};
enum ChosenSeedState
{
    SEED_FLYING_TO_BANK = 0,
    SEED_IN_BANK = 1,
    SEED_FLYING_TO_CHOOSER = 2,
    SEED_IN_CHOOSER = 3,
    SEED_PACKET_HIDDEN = 4
};
enum PickupMotion
{
    PICKUP_MOTION_FROM_SKY,
    PICKUP_MOTION_FROM_SKY_SLOW,
    PICKUP_MOTION_FROM_PLANT,
    PICKUP_MOTION_COIN,
    PICKUP_MOTION_LAWNMOWER_COIN,
    PICKUP_MOTION_FROM_PRESENT,
    PICKUP_MOTION_FROM_BOSS
};
enum PickupType
{
    PICKUP_NONE,
    PICKUP_SILVER,
    PICKUP_GOLD,
    PICKUP_DIAMOND,
    PICKUP_SUN,
    PICKUP_SMALLSUN,
    PICKUP_LARGESUN,
    PICKUP_FINAL_SEED_PACKET,
    PICKUP_TROPHY,
    PICKUP_SHOVEL,
    PICKUP_ALMANAC,
    PICKUP_CARKEYS,
    PICKUP_VASE,
    PICKUP_WATERING_CAN,
    PICKUP_TACO,
    PICKUP_NOTE,
    PICKUP_USABLE_SEED_PACKET,
    PICKUP_PRESENT_PLANT,
    PICKUP_AWARD_MONEY_BAG,
    PICKUP_AWARD_PRESENT,
    PICKUP_AWARD_BAG_DIAMOND,
    PICKUP_AWARD_SILVER_SUNFLOWER,
    PICKUP_AWARD_GOLD_SUNFLOWER,
    PICKUP_CHOCOLATE,
    PICKUP_AWARD_CHOCOLATE,
    PICKUP_PRESENT_MINIGAMES,
    PICKUP_PRESENT_PUZZLE_MODE,
    PICKUP_PRESENT_SURVIVAL_MODE,
};
enum CrazyDaveState
{
    CRAZY_DAVE_OFF,
    CRAZY_DAVE_ENTERING,
    CRAZY_DAVE_LEAVING,
    CRAZY_DAVE_IDLING,
    CRAZY_DAVE_TALKING,
    CRAZY_DAVE_HANDING_TALKING,
    CRAZY_DAVE_HANDING_IDLING
};
enum CursorType
{
    CURSOR_TYPE_NORMAL,
    CURSOR_TYPE_PLANT_FROM_BANK,
    CURSOR_TYPE_PLANT_FROM_USABLE_COIN,
    CURSOR_TYPE_PLANT_FROM_GLOVE,
    CURSOR_TYPE_PLANT_FROM_DUPLICATOR,
    CURSOR_TYPE_PLANT_FROM_WHEEL_BARROW,
    CURSOR_TYPE_SHOVEL,
    CURSOR_TYPE_HAMMER,
    CURSOR_TYPE_COBCANNON_TARGET,
    CURSOR_TYPE_WATERING_CAN,
    CURSOR_TYPE_FERTILIZER,
    CURSOR_TYPE_BUG_SPRAY,
    CURSOR_TYPE_PHONOGRAPH,
    CURSOR_TYPE_CHOCOLATE,
    CURSOR_TYPE_GLOVE,
    CURSOR_TYPE_MONEY_SIGN,
    CURSOR_TYPE_WHEEELBARROW,
    CURSOR_TYPE_TREE_FOOD
};
enum CursorMode
{
    CURSOR_MODE_NORMAL,
    CURSOR_MODE_INVISIBLE,
};
enum Dialogs
{
    DIALOG_NEW_GAME,
    DIALOG_OPTIONS,
    DIALOG_NEWOPTIONS,
    DIALOG_ALMANAC,
    DIALOG_STORE,
    DIALOG_PREGAME_NAG,
    DIALOG_LOAD_GAME,
    DIALOG_CONFIRM_UPDATE_CHECK,
    DIALOG_CHECKING_UPDATES,
    DIALOG_REGISTER_ERROR,
    DIALOG_COLORDEPTH_EXP,
    DIALOG_OPENURL_WAIT,
    DIALOG_OPENURL_FAIL,
    DIALOG_QUIT,
    DIALOG_HIGH_SCORES,
    DIALOG_NAG,
    DIALOG_INFO,
    DIALOG_GAME_OVER,
    DIALOG_LEVEL_COMPLETE,
    DIALOG_PAUSED,
    DIALOG_NO_MORE_MONEY,
    DIALOG_BONUS,
    DIALOG_CONFIRM_BACK_TO_MAIN,
    DIALOG_CONFIRM_RESTART,
    DIALOG_THANKS_FOR_REGISTERING,
    DIALOG_NOT_ENOUGH_MONEY,
    DIALOG_UPGRADED,
    DIALOG_NO_UPGRADE,
    DIALOG_CHOOSER_WARNING,
    DIALOG_USERDIALOG,
    DIALOG_CREATEUSER,
    DIALOG_CONFIRMDELETEUSER,
    DIALOG_RENAMEUSER,
    DIALOG_CREATEUSERERROR,
    DIALOG_RENAMEUSERERROR,
    DIALOG_CHEAT,
    DIALOG_CHEATERROR,
    DIALOG_CONTINUE,
    DIALOG_GETREADY,
    DIALOG_RESTARTCONFIRM,
    DIALOG_CONFIRMPURCHASE,
    DIALOG_CONFIRMSELL,
    DIALOG_TIMESUP,
    DIALOG_VIRTUALHELP,
    DIALOG_JUMPAHEAD,
    DIALOG_CRAZY_DAVE,
    DIALOG_STORE_PURCHASE,
    DIALOG_ZEN_SELL,
    DIALOG_MESSAGE,
    DIALOG_IMITATER,
    DIALOG_PURCHASE_PACKET_SLOT,
    DIALOG_CHALLENGE_PAGES,
    NUM_DIALOGS
};
enum DebugTextMode
{
    DEBUG_TEXT_NONE,
    DEBUG_TEXT_ZOMBIE_SPAWN,
    DEBUG_TEXT_MUSIC,
    DEBUG_TEXT_MEMORY,
    DEBUG_TEXT_COLLISION
};
enum DrawStringJustification
{
    DS_ALIGN_LEFT,
    DS_ALIGN_RIGHT,
    DS_ALIGN_CENTER,
    DS_ALIGN_LEFT_VERTICAL_MIDDLE,
    DS_ALIGN_RIGHT_VERTICAL_MIDDLE,
    DS_ALIGN_CENTER_VERTICAL_MIDDLE
};
enum DrawVariation
{
    VARIATION_NORMAL,
    VARIATION_IMITATER,
    VARIATION_MARIGOLD_WHITE,
    VARIATION_MARIGOLD_MAGENTA,
    VARIATION_MARIGOLD_ORANGE,
    VARIATION_MARIGOLD_PINK,
    VARIATION_MARIGOLD_LIGHT_BLUE,
    VARIATION_MARIGOLD_RED,
    VARIATION_MARIGOLD_BLUE,
    VARIATION_MARIGOLD_VIOLET,
    VARIATION_MARIGOLD_LAVENDER,
    VARIATION_MARIGOLD_YELLOW,
    VARIATION_MARIGOLD_LIGHT_GREEN,
    VARIATION_ZEN_GARDEN,
    VARIATION_ZEN_GARDEN_WATER,
    VARIATION_SPROUT_NO_FLOWER,
    VARIATION_IMITATER_LESS,
    VARIATION_AQUARIUM
};
enum EffectType
{
    EFFECT_PARTICLE,
    EFFECT_TRAIL,
    EFFECT_REANIM,
    EFFECT_ATTACHMENT,
    EFFECT_OTHER
};
enum EmitterType
{
    EMITTER_CIRCLE,
    EMITTER_BOX,
    EMITTER_BOX_PATH,
    EMITTER_CIRCLE_PATH,
    EMITTER_CIRCLE_EVEN_SPACING
};
enum GameMode
{
    GAMEMODE_ADVENTURE,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_1,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_2,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_3,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_4,
    GAMEMODE_SURVIVAL_NORMAL_STAGE_5,
    GAMEMODE_SURVIVAL_HARD_STAGE_1,
    GAMEMODE_SURVIVAL_HARD_STAGE_2,
    GAMEMODE_SURVIVAL_HARD_STAGE_3,
    GAMEMODE_SURVIVAL_HARD_STAGE_4,
    GAMEMODE_SURVIVAL_HARD_STAGE_5,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_1,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_2,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_3,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_4,
    GAMEMODE_SURVIVAL_ENDLESS_STAGE_5,
    GAMEMODE_CHALLENGE_WAR_AND_PEAS,
    GAMEMODE_CHALLENGE_WALLNUT_BOWLING,
    GAMEMODE_CHALLENGE_SLOT_MACHINE,
    GAMEMODE_CHALLENGE_RAINING_SEEDS,
    GAMEMODE_CHALLENGE_BEGHOULED,
    GAMEMODE_CHALLENGE_INVISIGHOUL,
    GAMEMODE_CHALLENGE_SEEING_STARS,
    GAMEMODE_CHALLENGE_ZOMBIQUARIUM,
    GAMEMODE_CHALLENGE_BEGHOULED_TWIST,
    GAMEMODE_CHALLENGE_LITTLE_TROUBLE,
    GAMEMODE_CHALLENGE_PORTAL_COMBAT,
    GAMEMODE_CHALLENGE_COLUMN,
    GAMEMODE_CHALLENGE_BOBSLED_BONANZA,
    GAMEMODE_CHALLENGE_SPEED,
    GAMEMODE_CHALLENGE_WHACK_A_ZOMBIE,
    GAMEMODE_CHALLENGE_LAST_STAND,
    GAMEMODE_CHALLENGE_WAR_AND_PEAS_2,
    GAMEMODE_CHALLENGE_WALLNUT_BOWLING_2,
    GAMEMODE_CHALLENGE_POGO_PARTY,
    GAMEMODE_CHALLENGE_FINAL_BOSS,
    GAMEMODE_CHALLENGE_ART_CHALLENGE_WALLNUT,
    GAMEMODE_CHALLENGE_SUNNY_DAY,
    GAMEMODE_CHALLENGE_RESODDED,
    GAMEMODE_CHALLENGE_BIG_TIME,
    GAMEMODE_CHALLENGE_ART_CHALLENGE_SUNFLOWER,
    GAMEMODE_CHALLENGE_AIR_RAID,
    GAMEMODE_CHALLENGE_ICE,
    GAMEMODE_CHALLENGE_ZEN_GARDEN,
    GAMEMODE_CHALLENGE_HIGH_GRAVITY,
    GAMEMODE_CHALLENGE_GRAVE_DANGER,
    GAMEMODE_CHALLENGE_SHOVEL,
    GAMEMODE_CHALLENGE_STORMY_NIGHT,
    GAMEMODE_CHALLENGE_BUNGEE_BLITZ,
    GAMEMODE_CHALLENGE_SQUIRREL,
    GAMEMODE_TREE_OF_WISDOM,
    GAMEMODE_SCARY_POTTER_1,
    GAMEMODE_SCARY_POTTER_2,
    GAMEMODE_SCARY_POTTER_3,
    GAMEMODE_SCARY_POTTER_4,
    GAMEMODE_SCARY_POTTER_5,
    GAMEMODE_SCARY_POTTER_6,
    GAMEMODE_SCARY_POTTER_7,
    GAMEMODE_SCARY_POTTER_8,
    GAMEMODE_SCARY_POTTER_9,
    GAMEMODE_SCARY_POTTER_ENDLESS,
    GAMEMODE_PUZZLE_I_ZOMBIE_1,
    GAMEMODE_PUZZLE_I_ZOMBIE_2,
    GAMEMODE_PUZZLE_I_ZOMBIE_3,
    GAMEMODE_PUZZLE_I_ZOMBIE_4,
    GAMEMODE_PUZZLE_I_ZOMBIE_5,
    GAMEMODE_PUZZLE_I_ZOMBIE_6,
    GAMEMODE_PUZZLE_I_ZOMBIE_7,
    GAMEMODE_PUZZLE_I_ZOMBIE_8,
    GAMEMODE_PUZZLE_I_ZOMBIE_9,
    GAMEMODE_PUZZLE_I_ZOMBIE_ENDLESS,
    GAMEMODE_UPSELL,
    GAMEMODE_INTRO,
    NUM_GAME_MODES,

    BASE_NUM_GAMEMODES = GAMEMODE_INTRO + 1
};
enum GameObjectType
{
    OBJECT_TYPE_NONE,
    OBJECT_TYPE_PLANT,
    OBJECT_TYPE_PROJECTILE,
    OBJECT_TYPE_COIN,
    OBJECT_TYPE_SEEDPACKET,
    OBJECT_TYPE_SHOVEL,
    OBJECT_TYPE_WATERING_CAN,
    OBJECT_TYPE_FERTILIZER,
    OBJECT_TYPE_BUG_SPRAY,
    OBJECT_TYPE_PHONOGRAPH,
    OBJECT_TYPE_CHOCOLATE,
    OBJECT_TYPE_GLOVE,
    OBJECT_TYPE_MONEY_SIGN,
    OBJECT_TYPE_WHEELBARROW,
    OBJECT_TYPE_TREE_FOOD,
    OBJECT_TYPE_NEXT_GARDEN,
    OBJECT_TYPE_MENU_BUTTON,
    OBJECT_TYPE_STORE_BUTTON,
    OBJECT_TYPE_SLOT_MACHINE_HANDLE,
    OBJECT_TYPE_SCARY_POT,
    OBJECT_TYPE_STINKY,
    OBJECT_TYPE_TREE_OF_WISDOM,
    OBJECT_TYPE_FASTMODE_BUTTON,
};
enum GameScenes
{
    SCENE_LOADING,
    SCENE_MENU,
    SCENE_LEVEL_INTRO,
    SCENE_PLAYING,
    SCENE_ZOMBIES_WON,
    SCENE_AWARD,
    SCENE_CREDIT,
    SCENE_CHALLENGE
};
enum GardenType
{
    GARDEN_MAIN,
    GARDEN_MUSHROOM,
    GARDEN_WHEELBARROW,
    GARDEN_AQUARIUM
};
enum GridItemType
{
    GRIDITEM_NONE,
    GRIDITEM_GRAVESTONE,
    GRIDITEM_CRATER,
    GRIDITEM_LADDER,
    GRIDITEM_PORTAL_CIRCLE,
    GRIDITEM_PORTAL_SQUARE,
    GRIDITEM_BRAIN,
    GRIDITEM_SCARY_POT,
    GRIDITEM_SQUIRREL,
    GRIDITEM_ZEN_TOOL,
    GRIDITEM_STINKY,
    GRIDITEM_RAKE,
    GRIDITEM_IZOMBIE_BRAIN
};
enum GridItemState
{
    GRIDITEM_STATE_NORMAL,
    GRIDITEM_STATE_GRAVESTONE_SPECIAL,
    GRIDITEM_STATE_PORTAL_CLOSED,
    GRIDITEM_STATE_SCARY_POT_QUESTION,
    GRIDITEM_STATE_SCARY_POT_LEAF,
    GRIDITEM_STATE_SCARY_POT_ZOMBIE,
    GRIDITEM_STATE_SQUIRREL_WAITING,
    GRIDITEM_STATE_SQUIRREL_PEEKING,
    GRIDITEM_STATE_SQUIRREL_RUNNING_UP,
    GRIDITEM_STATE_SQUIRREL_RUNNING_DOWN,
    GRIDITEM_STATE_SQUIRREL_RUNNING_LEFT,
    GRIDITEM_STATE_SQUIRREL_RUNNING_RIGHT,
    GRIDITEM_STATE_SQUIRREL_CAUGHT,
    GRIDITEM_STATE_SQUIRREL_ZOMBIE,
    GRIDITEM_STATE_ZEN_TOOL_WATERING_CAN,
    GRIDITEM_STATE_ZEN_TOOL_FERTILIZER,
    GRIDITEM_STATE_ZEN_TOOL_BUG_SPRAY,
    GRIDITEM_STATE_ZEN_TOOL_PHONOGRAPH,
    GRIDITEM_STATE_ZEN_TOOL_GOLD_WATERING_CAN,
    GRIDITEM_STINKY_WALKING_LEFT,
    GRIDITEM_STINKY_TURNING_LEFT,
    GRIDITEM_STINKY_WALKING_RIGHT,
    GRIDITEM_STINKY_TURNING_RIGHT,
    GRIDITEM_STINKY_SLEEPING,
    GRIDITEM_STINKY_FALLING_ASLEEP,
    GRIDITEM_STINKY_WAKING_UP,
    GRIDITEM_STATE_RAKE_ATTRACTING,
    GRIDITEM_STATE_RAKE_WAITING,
    GRIDITEM_STATE_RAKE_TRIGGERED,
    GRIDITEM_STATE_BRAIN_SQUISHED
};
enum GridSquareType
{
    GRIDSQUARE_NONE,
    GRIDSQUARE_GRASS,
    GRIDSQUARE_DIRT,
    GRIDSQUARE_POOL,
    GRIDSQUARE_HIGH_GROUND
};
enum HelmType
{
    HELMTYPE_NONE,
    HELMTYPE_TRAFFIC_CONE,
    HELMTYPE_PAIL,
    HELMTYPE_FOOTBALL,
    HELMTYPE_DIGGER,
    HELMTYPE_REDEYES,
    HELMTYPE_HEADBAND,
    HELMTYPE_BOBSLED,
    HELMTYPE_WALLNUT,
    HELMTYPE_TALLNUT
};
enum LawnMowerState
{
    MOWER_ROLLING_IN,
    MOWER_READY,
    MOWER_TRIGGERED,
    MOWER_SQUISHED
};
enum LawnMowerType
{
    LAWNMOWER_LAWN,
    LAWNMOWER_POOL,
    LAWNMOWER_ROOF,
    LAWNMOWER_SUPER_MOWER,
    NUM_MOWER_TYPES
};
enum MessageStyle
{
    MESSAGE_STYLE_OFF,
    MESSAGE_STYLE_TUTORIAL_LEVEL1,
    MESSAGE_STYLE_TUTORIAL_LEVEL1_STAY,
    MESSAGE_STYLE_TUTORIAL_LEVEL2,
    MESSAGE_STYLE_TUTORIAL_LATER,
    MESSAGE_STYLE_TUTORIAL_LATER_STAY,
    MESSAGE_STYLE_HINT_LONG,
    MESSAGE_STYLE_HINT_FAST,
    MESSAGE_STYLE_HINT_STAY,
    MESSAGE_STYLE_HINT_TALL_FAST,
    MESSAGE_STYLE_HINT_TALL_UNLOCKMESSAGE,

    MESSAGE_STYLE_HINT_TALL_LONG,
    MESSAGE_STYLE_BIG_MIDDLE,
    MESSAGE_STYLE_BIG_MIDDLE_FAST,
    MESSAGE_STYLE_HOUSE_NAME,
    MESSAGE_STYLE_HUGE_WAVE,
    MESSAGE_STYLE_SLOT_MACHINE,
    MESSAGE_STYLE_ZEN_GARDEN_LONG
};
enum MowerHeight
{
    MOWER_HEIGHT_LAND,
    MOWER_HEIGHT_DOWN_TO_POOL,
    MOWER_HEIGHT_IN_POOL,
    MOWER_HEIGHT_UP_TO_LAND
};
enum NotRecommend
{
    NOT_RECOMMENDED_NOCTURNAL,
    NOT_RECOMMENDED_NEEDS_POOL,
    NOT_RECOMMENDED_NEEDS_GRAVES,
    NOT_RECOMMENDED_NEEDS_FOG,
    NOT_RECOMMENDED_NEEDS_ROOF,
    NOT_RECOMMENDED_ON_ROOF,
    NOT_RECOMMENDED_FOR_CHALLENGE,
    NOT_RECOMMENDED_AT_NIGHT
};
enum ParticleEffect
{
    PARTICLE_NONE = -1,
    PARTICLE_MELONSPLASH,
    PARTICLE_WINTERMELON,
    PARTICLE_FUMECLOUD,
    PARTICLE_POPCORNSPLASH,
    PARTICLE_POWIE,
    PARTICLE_JACKEXPLODE,
    PARTICLE_ZOMBIE_HEAD,
    PARTICLE_ZOMBIE_ARM,
    PARTICLE_ZOMBIE_TRAFFIC_CONE,
    PARTICLE_ZOMBIE_PAIL,
    PARTICLE_ZOMBIE_HELMET,
    PARTICLE_ZOMBIE_FLAG,
    PARTICLE_ZOMBIE_DOOR,
    PARTICLE_ZOMBIE_NEWSPAPER,
    PARTICLE_ZOMBIE_HEADLIGHT,
    PARTICLE_POW,
    PARTICLE_ZOMBIE_POGO,
    PARTICLE_ZOMBIE_NEWSPAPER_HEAD,
    PARTICLE_ZOMBIE_BALLOON_HEAD,
    PARTICLE_SOD_ROLL,
    PARTICLE_GRAVE_STONE_RISE,
    PARTICLE_PLANTING,
    PARTICLE_PLANTING_POOL,
    PARTICLE_ZOMBIE_RISE,
    PARTICLE_GRAVE_BUSTER,
    PARTICLE_GRAVE_BUSTER_DIE,
    PARTICLE_POOL_SPLASH,
    PARTICLE_ICE_SPARKLE,
    PARTICLE_SEED_PACKET,
    PARTICLE_TALL_NUT_BLOCK,
    PARTICLE_DOOM,
    PARTICLE_DIGGER_RISE,
    PARTICLE_DIGGER_TUNNEL,
    PARTICLE_DANCER_RISE,
    PARTICLE_POOL_SPARKLY,
    PARTICLE_WALLNUT_EAT_SMALL,
    PARTICLE_WALLNUT_EAT_LARGE,
    PARTICLE_PEA_SPLAT,
    PARTICLE_BUTTER_SPLAT,
    PARTICLE_CABBAGE_SPLAT,
    PARTICLE_PUFF_SPLAT,
    PARTICLE_STAR_SPLAT,
    PARTICLE_ICE_TRAP,
    PARTICLE_SNOWPEA_SPLAT,
    PARTICLE_SNOWPEA_PUFF,
    PARTICLE_SNOWPEA_TRAIL,
    PARTICLE_LANTERN_SHINE,
    PARTICLE_SEED_PACKET_PICKUP,
    PARTICLE_POTATO_MINE,
    PARTICLE_POTATO_MINE_RISE,
    PARTICLE_PUFFSHROOM_TRAIL,
    PARTICLE_PUFFSHROOM_MUZZLE,
    PARTICLE_SEED_PACKET_FLASH,
    PARTICLE_WHACK_A_ZOMBIE_RISE,
    PARTICLE_ZOMBIE_LADDER,
    PARTICLE_UMBRELLA_REFLECT,
    PARTICLE_SEED_PACKET_PICK,
    PARTICLE_ICE_TRAP_ZOMBIE,
    PARTICLE_ICE_TRAP_RELEASE,
    PARTICLE_ZAMBONI_SMOKE,
    PARTICLE_GLOOMCLOUD,
    PARTICLE_ZOMBIE_POGO_HEAD,
    PARTICLE_ZAMBONI_TIRE,
    PARTICLE_ZAMBONI_EXPLOSION,
    PARTICLE_ZAMBONI_EXPLOSION2,
    PARTICLE_CATAPULT_EXPLOSION,
    PARTICLE_MOWER_CLOUD,
    PARTICLE_BOSS_ICE_BALL,
    PARTICLE_BLASTMARK,
    PARTICLE_COIN_PICKUP_ARROW,
    PARTICLE_PRESENT_PICKUP,
    PARTICLE_IMITATER_MORPH,
    PARTICLE_MOWERED_ZOMBIE_HEAD,
    PARTICLE_MOWERED_ZOMBIE_ARM,
    PARTICLE_ZOMBIE_HEAD_POOL,
    PARTICLE_ZOMBIE_BOSS_FIREBALL,
    PARTICLE_FIREBALL_DEATH,
    PARTICLE_ICEBALL_DEATH,
    PARTICLE_ICEBALL_TRAIL,
    PARTICLE_FIREBALL_TRAIL,
    PARTICLE_BOSS_EXPLOSION,
    PARTICLE_SCREEN_FLASH,
    PARTICLE_TROPHY_SPARKLE,
    PARTICLE_PORTAL_CIRCLE,
    PARTICLE_PORTAL_SQUARE,
    PARTICLE_POTTED_PLANT_GLOW,
    PARTICLE_POTTED_WATER_PLANT_GLOW,
    PARTICLE_POTTED_ZEN_GLOW,
    PARTICLE_MIND_CONTROL,
    PARTICLE_VASE_SHATTER,
    PARTICLE_VASE_SHATTER_LEAF,
    PARTICLE_VASE_SHATTER_ZOMBIE,
    PARTICLE_AWARD_PICKUP_ARROW,
    PARTICLE_ZOMBIE_SEAWEED,
    PARTICLE_ZOMBIE_MUSTACHE,
    PARTICLE_ZOMBIE_SUNGLASS,
    PARTICLE_ZOMBIE_PINATA,
    PARTICLE_DUST_SQUASH,
    PARTICLE_DUST_FOOT,
    PARTICLE_ZOMBIE_DAISIES,
    PARTICLE_CREDIT_STROBE,
    PARTICLE_CREDITS_RAYSWIPE,
    PARTICLE_CREDITS_ZOMBIEHEADWIPE,
    PARTICLE_STARBURST,
    PARTICLE_CREDITS_FOG,
    PARTICLE_PERSENT_PICK_UP_ARROW,
    NUM_PARTICLES
};
enum PlantPriority
{
    TOPPLANT_EATING_ORDER,
    TOPPLANT_DIGGING_ORDER,
    TOPPLANT_BUNGEE_ORDER,
    TOPPLANT_CATAPULT_ORDER,
    TOPPLANT_ZEN_TOOL_ORDER,
    TOPPLANT_ANY,
    TOPPLANT_ONLY_NORMAL_POSITION,
    TOPPLANT_ONLY_FLYING,
    TOPPLANT_ONLY_PUMPKIN,
    TOPPLANT_ONLY_UNDER_PLANT
};
enum PlantingReason
{
    PLANTING_OK,
    PLANTING_NOT_HERE,
    PLANTING_ONLY_ON_GRAVES,
    PLANTING_ONLY_IN_POOL,
    PLANTING_ONLY_ON_GROUND,
    PLANTING_NEEDS_POT,
    PLANTING_NOT_ON_ART,
    PLANTING_NOT_PASSED_LINE,
    PLANTING_NEEDS_UPGRADE,
    PLANTING_NOT_ON_GRAVE,
    PLANTING_NOT_ON_CRATER,
    PLANTING_NOT_ON_WATER,
    PLANTING_NEEDS_GROUND,
    PLANTING_NEEDS_SLEEPING
};
enum PlantRowType
{
    PLANTROW_DIRT,
    PLANTROW_NORMAL,
    PLANTROW_POOL,
    PLANTROW_HIGH_GROUND
};
enum PottedPlantAge
{
    PLANTAGE_SPROUT,
    PLANTAGE_SMALL,
    PLANTAGE_MEDIUM,
    PLANTAGE_FULL
};
enum PottedPlantNeed
{
    PLANTNEED_NONE,
    PLANTNEED_WATER,
    PLANTNEED_FERTILIZER,
    PLANTNEED_BUGSPRAY,
    PLANTNEED_PHONOGRAPH
};
enum ProjectileMotion
{
    MOTION_STRAIGHT,
    MOTION_LOBBED,
    MOTION_THREEPEATER,
    MOTION_BEE,
    MOTION_BEE_BACKWARDS,
    MOTION_PUFF,
    MOTION_BACKWARDS,
    MOTION_STAR,
    MOTION_FLOAT_OVER,
    MOTION_HOMING,
    MOTION_FREESTYLE
};
enum ProjectileType
{
    PROJECTILE_NONE = -1,
    PROJECTILE_PEA,
    PROJECTILE_SNOWPEA,
    PROJECTILE_CABBAGE,
    PROJECTILE_MELON,
    PROJECTILE_PUFF,
    PROJECTILE_WINTERMELON,
    PROJECTILE_FIREBALL,
    PROJECTILE_STAR,
    PROJECTILE_SPIKE,
    PROJECTILE_BASKETBALL,
    PROJECTILE_KERNEL,
    PROJECTILE_COBBIG,
    PROJECTILE_BUTTER,
    PROJECTILE_ZOMBIE_PEA,
    NUM_PROJECTILES
};
enum ReanimationType
{
    REANIM_NONE = -1,
    REANIM_LOADBAR_SPROUT,
    REANIM_LOADBAR_ZOMBIEHEAD,
    REANIM_SODROLL,
    REANIM_FINAL_WAVE,
    REANIM_PEASHOOTER,
    REANIM_WALLNUT,
    REANIM_LILYPAD,
    REANIM_SUNFLOWER,
    REANIM_LAWNMOWER,
    REANIM_READYSETPLANT,
    REANIM_CHERRYBOMB,
    REANIM_SQUASH,
    REANIM_DOOMSHROOM,
    REANIM_SNOWPEA,
    REANIM_REPEATER,
    REANIM_SUNSHROOM,
    REANIM_TALLNUT,
    REANIM_FUMESHROOM,
    REANIM_PUFFSHROOM,
    REANIM_HYPNOSHROOM,
    REANIM_CHOMPER,
    REANIM_ZOMBIE,
    REANIM_SUN,
    REANIM_POTATOMINE,
    REANIM_SPIKEWEED,
    REANIM_SPIKEROCK,
    REANIM_THREEPEATER,
    REANIM_MARIGOLD,
    REANIM_ICESHROOM,
    REANIM_ZOMBIE_FOOTBALL,
    REANIM_ZOMBIE_NEWSPAPER,
    REANIM_ZOMBIE_ZAMBONI,
    REANIM_SPLASH,
    REANIM_JALAPENO,
    REANIM_JALAPENO_FIRE,
    REANIM_COIN_SILVER,
    REANIM_ZOMBIE_CHARRED,
    REANIM_ZOMBIE_CHARRED_IMP,
    REANIM_ZOMBIE_CHARRED_DIGGER,
    REANIM_ZOMBIE_CHARRED_ZAMBONI,
    REANIM_ZOMBIE_CHARRED_CATAPULT,
    REANIM_ZOMBIE_CHARRED_GARGANTUAR,
    REANIM_SCRAREYSHROOM,
    REANIM_PUMPKIN,
    REANIM_PLANTERN,
    REANIM_TORCHWOOD,
    REANIM_SPLITPEA,
    REANIM_SEASHROOM,
    REANIM_BLOVER,
    REANIM_FLOWER_POT,
    REANIM_CACTUS,
    REANIM_DANCER,
    REANIM_TANGLEKELP,
    REANIM_STARFRUIT,
    REANIM_POLEVAULTER,
    REANIM_BALLOON,
    REANIM_GARGANTUAR,
    REANIM_IMP,
    REANIM_DIGGER,
    REANIM_DIGGER_DIRT,
    REANIM_ZOMBIE_DOLPHINRIDER,
    REANIM_POGO,
    REANIM_BACKUP_DANCER,
    REANIM_BOBSLED,
    REANIM_JACKINTHEBOX,
    REANIM_SNORKEL,
    REANIM_BUNGEE,
    REANIM_CATAPULT,
    REANIM_LADDER,
    REANIM_PUFF,
    REANIM_SLEEPING,
    REANIM_GRAVE_BUSTER,
    REANIM_ZOMBIES_WON,
    REANIM_MAGNETSHROOM,
    REANIM_BOSS,
    REANIM_CABBAGEPULT,
    REANIM_KERNELPULT,
    REANIM_MELONPULT,
    REANIM_COFFEEBEAN,
    REANIM_UMBRELLALEAF,
    REANIM_GATLINGPEA,
    REANIM_CATTAIL,
    REANIM_GLOOMSHROOM,
    REANIM_BOSS_ICEBALL,
    REANIM_BOSS_FIREBALL,
    REANIM_COBCANNON,
    REANIM_GARLIC,
    REANIM_GOLD_MAGNET,
    REANIM_WINTER_MELON,
    REANIM_TWIN_SUNFLOWER,
    REANIM_POOL_CLEANER,
    REANIM_ROOF_CLEANER,
    REANIM_FIRE_PEA,
    REANIM_IMITATER,
    REANIM_YETI,
    REANIM_BOSS_DRIVER,
    REANIM_LAWN_MOWERED_ZOMBIE,
    REANIM_CRAZY_DAVE,
    REANIM_TEXT_FADE_ON,
    REANIM_HAMMER,
    REANIM_SLOT_MACHINE_HANDLE,
    REANIM_CREDITS_FOOTBALL,
    REANIM_CREDITS_JACKBOX,
    REANIM_SELECTOR_SCREEN,
    REANIM_PORTAL_CIRCLE,
    REANIM_PORTAL_SQUARE,
    REANIM_ZENGARDEN_SPROUT,
    REANIM_ZENGARDEN_WATERINGCAN,
    REANIM_ZENGARDEN_FERTILIZER,
    REANIM_ZENGARDEN_BUGSPRAY,
    REANIM_ZENGARDEN_PHONOGRAPH,
    REANIM_DIAMOND,
    REANIM_ZOMBIE_HAND,
    REANIM_STINKY,
    REANIM_RAKE,
    REANIM_RAIN_CIRCLE,
    REANIM_RAIN_SPLASH,
    REANIM_ZOMBIE_SURPRISE,
    REANIM_COIN_GOLD,
    REANIM_TREEOFWISDOM,
    REANIM_TREEOFWISDOM_CLOUDS,
    REANIM_TREEOFWISDOM_TREEFOOD,
    REANIM_CREDITS_MAIN,
    REANIM_CREDITS_MAIN2,
    REANIM_CREDITS_MAIN3,
    REANIM_ZOMBIE_CREDITS_DANCE,
    REANIM_CREDITS_STAGE,
    REANIM_CREDITS_BIGBRAIN,
    REANIM_CREDITS_FLOWER_PETALS,
    REANIM_CREDITS_INFANTRY,
    REANIM_CREDITS_THROAT,
    REANIM_CREDITS_CRAZYDAVE,
    REANIM_CREDITS_BOSSDANCE,
    REANIM_ZOMBIE_CREDITS_SCREEN_DOOR,
    REANIM_ZOMBIE_CREDITS_CONEHEAD,
    REANIM_CREDITS_ZOMBIEARMY1,
    REANIM_CREDITS_ZOMBIEARMY2,
    REANIM_CREDITS_TOMBSTONES,
    REANIM_CREDITS_SOLARPOWER,
    REANIM_CREDITS_ANYHOUR,
    REANIM_CREDITS_WEARETHEUNDEAD,
    REANIM_CREDITS_DISCOLIGHTS,
    REANIM_FLAG,
    NUM_REANIMS
};
enum ReanimLoopType
{
    REANIM_LOOP,
    REANIM_LOOP_FULL_LAST_FRAME,
    REANIM_PLAY_ONCE,
    REANIM_PLAY_ONCE_AND_HOLD,
    REANIM_PLAY_ONCE_FULL_LAST_FRAME,
    REANIM_PLAY_ONCE_FULL_LAST_FRAME_AND_HOLD
};
enum RenderLayer
{
    RENDER_LAYER_ROW_OFFSET = 10000,
    RENDER_LAYER_UI_BOTTOM = 100000,
    RENDER_LAYER_GROUND = 200000,
    RENDER_LAYER_LAWN = 300000,
    RENDER_LAYER_GRAVE_STONE = 301000,
    RENDER_LAYER_PLANT = 302000,
    RENDER_LAYER_ZOMBIE = 303000,
    RENDER_LAYER_BOSS = 304000,
    RENDER_LAYER_PROJECTILE = 305000,
    RENDER_LAYER_LAWN_MOWER = 306000,
    RENDER_LAYER_PARTICLE = 307000,
    RENDER_LAYER_TOP = 400000,
    RENDER_LAYER_FOG = 500000,
    RENDER_LAYER_COIN_BANK = 600000,
    RENDER_LAYER_UI_TOP = 700000,
    RENDER_LAYER_ABOVE_UI = 800000,
    RENDER_LAYER_SCREEN_FADE = 900000
};
enum RenderObjectType
{
    RENDER_ITEM_COIN,
    RENDER_ITEM_PROJECTILE,
    RENDER_ITEM_ZOMBIE,
    RENDER_ITEM_ZOMBIE_SHADOW,
    RENDER_ITEM_ZOMBIE_BUNGEE_TARGET,
    RENDER_ITEM_PLANT,
    RENDER_ITEM_PLANT_OVERLAY,
    RENDER_ITEM_PLANT_MAGNET_ITEMS,
    RENDER_ITEM_CURSOR_PREVIEW,
    RENDER_ITEM_PARTICLE,
    RENDER_ITEM_REANIMATION,
    RENDER_ITEM_ICE,
    RENDER_ITEM_TOP_UI,
    RENDER_ITEM_FOG,
    RENDER_ITEM_STORM,
    RENDER_ITEM_BOTTOM_UI,
    RENDER_ITEM_BACKDROP,
    RENDER_ITEM_DOOR_MASK,
    RENDER_ITEM_COIN_BANK,
    RENDER_ITEM_PROJECTILE_SHADOW,
    RENDER_ITEM_MOWER,
    RENDER_ITEM_SCREEN_FADE,
    RENDER_ITEM_BOSS_PART,
    RENDER_ITEM_GRID_ITEM,
    RENDER_ITEM_GRID_ITEM_OVERLAY,
    RENDER_ITEM_HEALTHBAR_ZOMBIE,
    RENDER_ITEM_HEALTHBAR_PLANT
};
enum ScaryPotType
{
    SCARYPOT_NONE,
    SCARYPOT_SEED,
    SCARYPOT_ZOMBIE,
    SCARYPOT_SUN
};
enum SeedChooserState
{
    CHOOSE_NORMAL,
    CHOOSE_VIEW_LAWN
};
enum SeedType
{
    SEED_NONE = -1,
    SEED_PEASHOOTER,
    SEED_SUNFLOWER,
    SEED_CHERRYBOMB,
    SEED_WALLNUT,
    SEED_POTATOMINE,
    SEED_SNOWPEA,
    SEED_CHOMPER,
    SEED_REPEATER,
    SEED_PUFFSHROOM,
    SEED_SUNSHROOM,
    SEED_FUMESHROOM,
    SEED_GRAVEBUSTER,
    SEED_HYPNOSHROOM,
    SEED_SCAREDYSHROOM,
    SEED_ICESHROOM,
    SEED_DOOMSHROOM,
    SEED_LILYPAD,
    SEED_SQUASH,
    SEED_THREEPEATER,
    SEED_TANGLEKELP,
    SEED_JALAPENO,
    SEED_SPIKEWEED,
    SEED_TORCHWOOD,
    SEED_TALLNUT,
    SEED_SEASHROOM,
    SEED_PLANTERN,
    SEED_CACTUS,
    SEED_BLOVER,
    SEED_SPLITPEA,
    SEED_STARFRUIT,
    SEED_PUMPKINSHELL,
    SEED_MAGNETSHROOM,
    SEED_CABBAGEPULT,
    SEED_FLOWERPOT,
    SEED_KERNELPULT,
    SEED_INSTANT_COFFEE,
    SEED_GARLIC,
    SEED_UMBRELLA,
    SEED_MARIGOLD,
    SEED_MELONPULT,
    SEED_GATLINGPEA,
    SEED_TWINSUNFLOWER,
    SEED_GLOOMSHROOM,
    SEED_CATTAIL,
    SEED_WINTERMELON,
    SEED_GOLD_MAGNET,
    SEED_SPIKEROCK,
    SEED_COBCANNON,
    SEED_IMITATER,
    SEED_EXPLODE_O_NUT,
    SEED_GIANT_WALLNUT,
    SEED_SPROUT,
    SEED_LEFTPEATER,
    NUM_SEED_TYPES,
    SEED_BEGHOULED_BUTTON_SHUFFLE,
    SEED_BEGHOULED_BUTTON_CRATER,
    SEED_SLOT_MACHINE_SUN,
    SEED_SLOT_MACHINE_DIAMOND,
    SEED_ZOMBIQUARIUM_SNORKLE,
    SEED_ZOMBIQUARIUM_TROPHY,
    SEED_ZOMBIE_NORMAL,
    SEED_ZOMBIE_TRAFFIC_CONE,
    SEED_ZOMBIE_POLEVAULTER,
    SEED_ZOMBIE_PAIL,
    SEED_ZOMBIE_LADDER,
    SEED_ZOMBIE_DIGGER,
    SEED_ZOMBIE_BUNGEE,
    SEED_ZOMBIE_FOOTBALL,
    SEED_ZOMBIE_BALLOON,
    SEED_ZOMBIE_SCREEN_DOOR,
    SEED_ZOMBONI,
    SEED_ZOMBIE_POGO,
    SEED_ZOMBIE_DANCER,
    SEED_ZOMBIE_GARGANTUAR,
    SEED_ZOMBIE_IMP,
    NUM_SEEDS_IN_CHOOSER = SEED_IMITATER + 1,
    BASE_NUM_SEED_TYPES = 0x35,
    SEED_UNOCCUPIED_START = 0x4B
};
enum ShieldType
{
    SHIELDTYPE_NONE,
    SHIELDTYPE_DOOR,
    SHIELDTYPE_NEWSPAPER,
    SHIELDTYPE_LADDER
};
enum StoreItem
{
    STORE_ITEM_PLANT_GATLINGPEA,
    STORE_ITEM_PLANT_TWINSUNFLOWER,
    STORE_ITEM_PLANT_GLOOMSHROOM,
    STORE_ITEM_PLANT_CATTAIL,
    STORE_ITEM_PLANT_WINTERMELON,
    STORE_ITEM_PLANT_GOLD_MAGNET,
    STORE_ITEM_PLANT_SPIKEROCK,
    STORE_ITEM_PLANT_COBCANNON,
    STORE_ITEM_PLANT_IMITATER,
    STORE_ITEM_BONUS_LAWN_MOWER,
    STORE_ITEM_POTTED_MARIGOLD_1,
    STORE_ITEM_POTTED_MARIGOLD_2,
    STORE_ITEM_POTTED_MARIGOLD_3,
    STORE_ITEM_GOLD_WATERINGCAN,
    STORE_ITEM_FERTILIZER,
    STORE_ITEM_BUG_SPRAY,
    STORE_ITEM_PHONOGRAPH,
    STORE_ITEM_GARDENING_GLOVE,
    STORE_ITEM_MUSHROOM_GARDEN,
    STORE_ITEM_WHEEL_BARROW,
    STORE_ITEM_STINKY_THE_SNAIL,
    STORE_ITEM_PACKET_UPGRADE,
    STORE_ITEM_POOL_CLEANER,
    STORE_ITEM_ROOF_CLEANER,
    STORE_ITEM_RAKE,
    STORE_ITEM_AQUARIUM_GARDEN,
    STORE_ITEM_CHOCOLATE,
    STORE_ITEM_TREE_OF_WISDOM,
    STORE_ITEM_TREE_FOOD,
    STORE_ITEM_FIRSTAID,
    STORE_ITEM_PVZ,
    STORE_ITEM_INVALID = -1
};
enum StorePages
{
    STORE_PAGE_SLOT_UPGRADES,
    STORE_PAGE_PLANT_UPGRADES,
    STORE_PAGE_ZEN1,
    STORE_PAGE_ZEN2,
    NUM_STORE_PAGES
};
enum TodCurves
{
    CURVE_CONSTANT,
    CURVE_LINEAR,
    CURVE_EASE_IN,
    CURVE_EASE_OUT,
    CURVE_EASE_IN_OUT,
    CURVE_EASE_IN_OUT_WEAK,
    CURVE_FAST_IN_OUT,
    CURVE_FAST_IN_OUT_WEAK,
    CURVE_WEAK_FAST_IN_OUT,
    CURVE_BOUNCE,
    CURVE_BOUNCE_FAST_MIDDLE,
    CURVE_BOUNCE_SLOW_MIDDLE,
    CURVE_SIN_WAVE,
    CURVE_EASE_SIN_WAVE
};
enum TrialType
{
    TRIALTYPE_NONE,
    TRIALTYPE_STAGELOCKED
};
enum TutorialState
{
    TUTORIAL_OFF,
    TUTORIAL_LEVEL_1_PICK_UP_PEASHOOTER,
    TUTORIAL_LEVEL_1_PLANT_PEASHOOTER,
    TUTORIAL_LEVEL_1_REFRESH_PEASHOOTER,
    TUTORIAL_LEVEL_1_COMPLETED,
    TUTORIAL_LEVEL_2_PICK_UP_SUNFLOWER,
    TUTORIAL_LEVEL_2_PLANT_SUNFLOWER,
    TUTORIAL_LEVEL_2_REFRESH_SUNFLOWER,
    TUTORIAL_LEVEL_2_COMPLETED,
    TUTORIAL_MORESUN_PICK_UP_SUNFLOWER,
    TUTORIAL_MORESUN_PLANT_SUNFLOWER,
    TUTORIAL_MORESUN_REFRESH_SUNFLOWER,
    TUTORIAL_MORESUN_COMPLETED,
    TUTORIAL_SLOT_MACHINE_PULL,
    TUTORIAL_SLOT_MACHINE_COMPLETED,
    TUTORIAL_SHOVEL_PICKUP,
    TUTORIAL_SHOVEL_DIG,
    TUTORIAL_SHOVEL_KEEP_DIGGING,
    TUTORIAL_SHOVEL_COMPLETED,
    TUTORIAL_ZOMBIQUARIUM_BUY_SNORKEL,
    TUTORIAL_ZOMBIQUARIUM_BOUGHT_SNORKEL,
    TUTORIAL_ZOMBIQUARIUM_CLICK_TROPHY,
    TUTORIAL_ZEN_GARDEN_PICKUP_WATER,
    TUTORIAL_ZEN_GARDEN_WATER_PLANT,
    TUTORIAL_ZEN_GARDEN_KEEP_WATERING,
    TUTORIAL_ZEN_GARDEN_VISIT_STORE,
    TUTORIAL_ZEN_GARDEN_FERTILIZE_PLANTS,
    TUTORIAL_ZEN_GARDEN_COMPLETED,
    TUTORIAL_WHACK_A_ZOMBIE_BEFORE_PICK_SEED,
    TUTORIAL_WHACK_A_ZOMBIE_PICK_SEED,
    TUTORIAL_WHACK_A_ZOMBIE_COMPLETED
};
enum UnlockingState
{
    UNLOCK_OFF,
    UNLOCK_SHAKING,
    UNLOCK_FADING
};
enum ZombieHeight
{
    HEIGHT_ZOMBIE_NORMAL,
    HEIGHT_IN_TO_POOL,
    HEIGHT_OUT_OF_POOL,
    HEIGHT_DRAGGED_UNDER,
    HEIGHT_UP_TO_HIGH_GROUND,
    HEIGHT_DOWN_OFF_HIGH_GROUND,
    HEIGHT_UP_LADDER,
    HEIGHT_FALLING,
    HEIGHT_IN_TO_CHIMNEY,
    HEIGHT_GETTING_BUNGEE_DROPPED,
    HEIGHT_ZOMBIQUARIUM
};
enum ZombiePhase
{
    PHASE_ZOMBIE_NORMAL,
    PHASE_ZOMBIE_DYING,
    PHASE_ZOMBIE_BURNED,
    PHASE_ZOMBIE_MOWERED,
    PHASE_BUNGEE_DIVING,
    PHASE_BUNGEE_DIVING_SCREAMING,
    PHASE_BUNGEE_AT_BOTTOM,
    PHASE_BUNGEE_GRABBING,
    PHASE_BUNGEE_RISING,
    PHASE_BUNGEE_HIT_OUCHY,
    PHASE_BUNGEE_CUTSCENE,
    PHASE_POLEVAULTER_PRE_VAULT,
    PHASE_POLEVAULTER_IN_VAULT,
    PHASE_POLEVAULTER_POST_VAULT,
    PHASE_RISING_FROM_GRAVE,
    PHASE_JACK_IN_THE_BOX_RUNNING,
    PHASE_JACK_IN_THE_BOX_POPPING,
    PHASE_BOBSLED_SLIDING,
    PHASE_BOBSLED_BOARDING,
    PHASE_BOBSLED_CRASHING,
    PHASE_POGO_BOUNCING,
    PHASE_POGO_HIGH_BOUNCE_1,
    PHASE_POGO_HIGH_BOUNCE_2,
    PHASE_POGO_HIGH_BOUNCE_3,
    PHASE_POGO_HIGH_BOUNCE_4,
    PHASE_POGO_HIGH_BOUNCE_5,
    PHASE_POGO_HIGH_BOUNCE_6,
    PHASE_POGO_FORWARD_BOUNCE_2,
    PHASE_POGO_FORWARD_BOUNCE_7,
    PHASE_NEWSPAPER_READING,
    PHASE_NEWSPAPER_MADDENING,
    PHASE_NEWSPAPER_MAD,
    PHASE_DIGGER_TUNNELING,
    PHASE_DIGGER_RISING,
    PHASE_DIGGER_TUNNELING_PAUSE_WITHOUT_AXE,
    PHASE_DIGGER_RISE_WITHOUT_AXE,
    PHASE_DIGGER_STUNNED,
    PHASE_DIGGER_WALKING,
    PHASE_DIGGER_WALKING_WITHOUT_AXE,
    PHASE_DIGGER_CUTSCENE,
    PHASE_DANCER_DANCING_IN,
    PHASE_DANCER_SNAPPING_FINGERS,
    PHASE_DANCER_SNAPPING_FINGERS_WITH_LIGHT,
    PHASE_DANCER_SNAPPING_FINGERS_HOLD,
    PHASE_DANCER_DANCING_LEFT,
    PHASE_DANCER_WALK_TO_RAISE,
    PHASE_DANCER_RAISE_LEFT_1,
    PHASE_DANCER_RAISE_RIGHT_1,
    PHASE_DANCER_RAISE_LEFT_2,
    PHASE_DANCER_RAISE_RIGHT_2,
    PHASE_DANCER_RISING,
    PHASE_DOLPHIN_WALKING,
    PHASE_DOLPHIN_INTO_POOL,
    PHASE_DOLPHIN_RIDING,
    PHASE_DOLPHIN_IN_JUMP,
    PHASE_DOLPHIN_WALKING_IN_POOL,
    PHASE_DOLPHIN_WALKING_WITHOUT_DOLPHIN,
    PHASE_SNORKEL_WALKING,
    PHASE_SNORKEL_INTO_POOL,
    PHASE_SNORKEL_WALKING_IN_POOL,
    PHASE_SNORKEL_UP_TO_EAT,
    PHASE_SNORKEL_EATING_IN_POOL,
    PHASE_SNORKEL_DOWN_FROM_EAT,
    PHASE_ZOMBIQUARIUM_ACCEL,
    PHASE_ZOMBIQUARIUM_DRIFT,
    PHASE_ZOMBIQUARIUM_BACK_AND_FORTH,
    PHASE_ZOMBIQUARIUM_BITE,
    PHASE_CATAPULT_LAUNCHING,
    PHASE_CATAPULT_RELOADING,
    PHASE_GARGANTUAR_THROWING,
    PHASE_GARGANTUAR_SMASHING,
    PHASE_IMP_GETTING_THROWN,
    PHASE_IMP_LANDING,
    PHASE_BALLOON_FLYING,
    PHASE_BALLOON_POPPING,
    PHASE_BALLOON_WALKING,
    PHASE_LADDER_CARRYING,
    PHASE_LADDER_PLACING,
    PHASE_BOSS_ENTER,
    PHASE_BOSS_IDLE,
    PHASE_BOSS_SPAWNING,
    PHASE_BOSS_STOMPING,
    PHASE_BOSS_BUNGEES_ENTER,
    PHASE_BOSS_BUNGEES_DROP,
    PHASE_BOSS_BUNGEES_LEAVE,
    PHASE_BOSS_DROP_RV,
    PHASE_BOSS_HEAD_ENTER,
    PHASE_BOSS_HEAD_IDLE_BEFORE_SPIT,
    PHASE_BOSS_HEAD_IDLE_AFTER_SPIT,
    PHASE_BOSS_HEAD_SPIT,
    PHASE_BOSS_HEAD_LEAVE,
    PHASE_YETI_RUNNING,
    PHASE_SQUASH_PRE_LAUNCH,
    PHASE_SQUASH_RISING,
    PHASE_SQUASH_FALLING,
    PHASE_SQUASH_DONE_FALLING
};
enum ZombieType
{
    ZOMBIE_NONE = -1,
    ZOMBIE_INVALID = -1,
    ZOMBIE_NORMAL,
    ZOMBIE_FLAG,
    ZOMBIE_TRAFFIC_CONE,
    ZOMBIE_POLEVAULTER,
    ZOMBIE_PAIL,
    ZOMBIE_NEWSPAPER,
    ZOMBIE_DOOR,
    ZOMBIE_FOOTBALL,
    ZOMBIE_DANCER,
    ZOMBIE_BACKUP_DANCER,
    ZOMBIE_DUCKY_TUBE,
    ZOMBIE_SNORKEL,
    ZOMBIE_ZAMBONI,
    ZOMBIE_BOBSLED,
    ZOMBIE_DOLPHIN_RIDER,
    ZOMBIE_JACK_IN_THE_BOX,
    ZOMBIE_BALLOON,
    ZOMBIE_DIGGER,
    ZOMBIE_POGO,
    ZOMBIE_YETI,
    ZOMBIE_BUNGEE,
    ZOMBIE_LADDER,
    ZOMBIE_CATAPULT,
    ZOMBIE_GARGANTUAR,
    ZOMBIE_IMP,
    ZOMBIE_BOSS,
    ZOMBIE_REDEYE_GARGANTUAR,
    ZOMBIE_PEA_HEAD,
    ZOMBIE_WALLNUT_HEAD,
    ZOMBIE_JALAPENO_HEAD,
    ZOMBIE_GATLING_HEAD,
    ZOMBIE_SQUASH_HEAD,
    ZOMBIE_TALLNUT_HEAD,
    NUM_ZOMBIE_TYPES,
    ZOMBIE_CACHED_POLEVAULTER_WITH_POLE,
    NUM_CACHED_ZOMBIE_TYPES,
    NUM_ZOMBIES_IN_ALMANAC = ZOMBIE_BOSS + 1,
    BASE_NUM_ZOMBIE_TYPES = 0x21
};

// Extras
/* -VB
* Damage Flags Guide:
0000 0001: IsPiercingDamage. When true damage will ignore shields (not including helmets.)

0000 0010: CarriesOver. When true, if this damage kills the zombie's shield, it will carry over the damage to the zombie's body. If not, it will block the damage entirely and drop the shield.
Ex: Say the zombie has 100 BodyHP, 1 ShieldHP, and the damage instance deals 30 DMG. If this flag is true, it will firstly take the ShieldHP, dropping the shield, with a remaining 29 points of damage. These points will then damage the body (or helmet, if it exists,) dealing 29 damage to either the body or helmet. If this flag is off, however, this 1 ShieldHP will completely cancel out this damage, dropping the shield but keeping the BodyHP at a hundred.

0000 0100: IsChilling. When true, this hit will chill the zombie(s) it hits.

0000 1000: IsFlashing. When true, the hit will cause a slight flash to indicate damage has been taken.

0001 0000: IsBlocking. When true, indicates that this damage type is blocking damage (produces cool particles that indicate blocking.) Additionally, will block Bobsled zombies' progression. (Yeah I didn't know this happens either but apparently TallNuts can crash and damage the bobsled)

0010 0000: IsUnderground. When true, will pop zombie tires.
*/
enum DamageFlags
{
    DAMAGE_NORMAL       = 0b00000000,
    DAMAGE_PIERCING     = 0b00000001,
    DAMAGE_CARRY_OVER   = 0b00000010,
    DAMAGE_CHILLING     = 0b00000100,
    DAMAGE_FLASHING     = 0b00001000,
    DAMAGE_BLOCKING     = 0b00010000,
    DAMAGE_UNDERGROUND  = 0b00100000
};
struct DamageFlag
{
    bool mPiercing      : 1 = 0;
    bool mCarriesOver   : 1 = 0;
    bool mChilling      : 1 = 0;
    bool mCausesFlash   : 1 = 0;
    bool mBlocksZombies : 1 = 0;
    bool mUnderground   : 1 = 0;

    DamageFlag() = default;
    DamageFlag(DamageFlags Flags) { *(unsigned char*)this = (unsigned char)Flags; }
    DamageFlag(unsigned char Flags) { *(unsigned char*)this = Flags; }
    operator DamageFlags() { return (DamageFlags)*this; }
};

enum DamageRangeFlags
{
    DAMAGES_GROUND,
    DAMAGES_FLYING,
    DAMAGES_SUBMERGED,
    DAMAGES_DOG,
    DAMAGES_OFF_GROUND,
    DAMAGES_DYING,
    DAMAGES_UNDERGROUND,
    DAMAGES_ONLY_MINDCONTROLLED
};

// Specific Enums
enum PlantState
{
    STATE_NOTREADY = 0x0,
    STATE_READY = 0x1,
    STATE_DOINGSPECIAL = 0x2,
    STATE_SQUASH_LOOK = 0x3,
    STATE_SQUASH_PRE_LAUNCH = 0x4,
    STATE_SQUASH_RISING = 0x5,
    STATE_SQUASH_FALLING = 0x6,
    STATE_SQUASH_DONE_FALLING = 0x7,
    STATE_GRAVEBUSTER_LANDING = 0x8,
    STATE_GRAVEBUSTER_EATING = 0x9,
    STATE_CHOMPER_BITING = 0xA,
    STATE_CHOMPER_BITING_GOT_ONE = 0xB,
    STATE_CHOMPER_BITING_MISSED = 0xC,
    STATE_CHOMPER_DIGESTING = 0xD,
    STATE_CHOMPER_SWALLOWING = 0xE,
    STATE_POTATO_RISING = 0xF,
    STATE_POTATO_ARMED = 0x10,
    STATE_POTATO_MASHED = 0x11,
    STATE_SPIKEWEED_ATTACKING = 0x12,
    STATE_SPIKEWEED_ATTACKING_2 = 0x13,
    STATE_SCAREDYSHROOM_LOWERING = 0x14,
    STATE_SCAREDYSHROOM_SCARED = 0x15,
    STATE_SCAREDYSHROOM_RAISING = 0x16,
    STATE_SUNSHROOM_SMALL = 0x17,
    STATE_SUNSHROOM_GROWING = 0x18,
    STATE_SUNSHROOM_BIG = 0x19,
    STATE_MAGNETSHROOM_SUCKING = 0x1A,
    STATE_MAGNETSHROOM_CHARGING = 0x1B,
    STATE_BOWLING_UP = 0x1C,
    STATE_BOWLING_DOWN = 0x1D,
    STATE_CACTUS_LOW = 0x1E,
    STATE_CACTUS_RISING = 0x1F,
    STATE_CACTUS_HIGH = 0x20,
    STATE_CACTUS_LOWERING = 0x21,
    STATE_TANGLEKELP_GRABBING = 0x22,
    STATE_COBCANNON_ARMING = 0x23,
    STATE_COBCANNON_LOADING = 0x24,
    STATE_COBCANNON_READY = 0x25,
    STATE_COBCANNON_FIRING = 0x26,
    STATE_KERNELPULT_BUTTER = 0x27,
    STATE_UMBRELLA_TRIGGERED = 0x28,
    STATE_UMBRELLA_REFLECTING = 0x29,
    STATE_IMITATER_MORPHING = 0x2A,
    STATE_ZEN_GARDEN_WATERED = 0x2B,
    STATE_ZEN_GARDEN_NEEDY = 0x2C,
    STATE_ZEN_GARDEN_HAPPY = 0x2D,
    STATE_MARIGOLD_ENDING = 0x2E,
    STATE_FLOWERPOT_INVULNERABLE = 0x2F,
    STATE_LILYPAD_INVULNERABLE = 0x30
};
enum MagnetItemType
{
    MAGNET_ITEM_NONE,
    MAGNET_ITEM_PAIL_1,
    MAGNET_ITEM_PAIL_2,
    MAGNET_ITEM_PAIL_3,
    MAGNET_ITEM_FOOTBALL_HELMET_1,
    MAGNET_ITEM_FOOTBALL_HELMET_2,
    MAGNET_ITEM_FOOTBALL_HELMET_3,
    MAGNET_ITEM_DOOR_1,
    MAGNET_ITEM_DOOR_2,
    MAGNET_ITEM_DOOR_3,
    MAGNET_ITEM_POGO_1,
    MAGNET_ITEM_POGO_2,
    MAGNET_ITEM_POGO_3,
    MAGNET_ITEM_JACK_IN_THE_BOX,
    MAGNET_ITEM_LADDER_1,
    MAGNET_ITEM_LADDER_2,
    MAGNET_ITEM_LADDER_3,
    MAGNET_ITEM_LADDER_PLACED,
    MAGNET_ITEM_SILVER_COIN,
    MAGNET_ITEM_GOLD_COIN,
    MAGNET_ITEM_DIAMOND,
    MAGNET_ITEM_PICK_AXE
};
enum PlantSubClass
{
    SUBCLASS_NORMAL,
    SUBCLASS_SHOOTER
};
enum PlantOnBungeeState
{
    NOT_ON_BUNGEE,
    GETTING_GRABBED_BY_BUNGEE,
    RISING_WITH_BUNGEE
};

enum ParticleTracks
{
    TRACK_PARTICLE_RED,
    TRACK_PARTICLE_GREEN,
    TRACK_PARTICLE_BLUE,
    TRACK_PARTICLE_ALPHA,
    TRACK_PARTICLE_BRIGHTNESS,
    TRACK_PARTICLE_SPIN_SPEED,
    TRACK_PARTICLE_SPIN_ANGLE,
    TRACK_PARTICLE_SCALE,
    TRACK_PARTICLE_STRETCH,
    TRACK_PARTICLE_COLLISION_REFLECT,
    TRACK_PARTICLE_COLLISION_SPIN,
    TRACK_PARTICLE_CLIP_TOP,
    TRACK_PARTICLE_CLIP_BOTTOM,
    TRACK_PARTICLE_CLIP_LEFT,
    TRACK_PARTICLE_CLIP_RIGHT,
    TRACK_PARTICLE_ANIMATION_RATE,
    NUM_PARTICLE_TRACKS
};
enum ParticleSystemTracks
{
    TRACK_SPAWN_RATE,
    TRACK_SPAWN_MIN_ACTIVE,
    TRACK_SPAWN_MAX_ACTIVE,
    TRACK_SPAWN_MAX_LAUNCHED,
    TRACK_EMITTER_PATH,
    TRACK_SYSTEM_RED,
    TRACK_SYSTEM_GREEN,
    TRACK_SYSTEM_BLUE,
    TRACK_SYSTEM_ALPHA,
    TRACK_SYSTEM_BRIGHTNESS,
    NUM_SYSTEM_TRACKS
};
enum ParticleFieldType
{
    FIELD_INVALID,
    FIELD_FRICTION,
    FIELD_ACCELERATION,
    FIELD_ATTRACTOR,
    FIELD_MAX_VELOCITY,
    FIELD_VELOCITY,
    FIELD_POSITION,
    FIELD_SYSTEM_POSITION,
    FIELD_GROUND_CONSTRAINT,
    FIELD_SHAKE,
    FIELD_CIRCLE,
    FIELD_AWAY,
    PARTICLE_FIELD_COUNT
};
enum ParticleFlags
{
    PARTICLE_RANDOM_LAUNCH_SPIN,
    PARTICLE_ALIGN_LAUNCH_SPIN,
    PARTICLE_ALIGN_TO_PIXELS,
    PARTICLE_SYSTEM_LOOPS,
    PARTICLE_PARTICLE_LOOPS,
    PARTICLE_PARTICLES_DONT_FOLLOW,
    PARTICLE_RANDOM_START_TIME,
    PARTICLE_DIE_IF_OVERLOADED,
    PARTICLE_ADDITIVE,
    PARTICLE_FULLSCREEN,
    PARTICLE_SOFTWARE_ONLY,
    PARTICLE_HARDWARE_ONLY
};

enum TrailFlags { TRAIL_FLAG_LOOPS };
enum TrailTracks
{
    TRACK_WIDTH_OVER_LENGTH,
    TRACK_WIDTH_OVER_TIME,
    TRACK_ALPHA_OVER_LENGTH,
    TRACK_ALPHA_OVER_TIME,
    NUM_TRAIL_TRACKS
};
enum TrailType
{
    TRAIL_NONE = -1,
    TRAIL_ICE,
    NUM_TRAILS,
};