name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
              
            - name: Setup Ninja
              uses: seanmiddleditch/gha-setup-ninja@v5
      
            - name: Configure Project
              id: cmake-action
              uses: ./cmake-action
              with:
                generator: Ninja
                run-build: false
      
            - name: Build Project
              run: ninja -C ${{ steps.cmake-action.outputs.build-dir }}