name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
    build:
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
            os: [windows]
            arch: [x86]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Setup Ninja and CMake
              uses: lukka/get-cmake@latest
            - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
              uses: lukka/run-cmake@v10
              with:
                buildPreset: 'x86-release'