name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Install CMake
              uses: lukka/get-cmake@latest
            - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
              uses: lukka/run-cmake@v10
              with:
                buildPresetAdditionalArgs: "['--preset x86-release']"