name: build

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
    build:
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
            os: [windows]
            arch: [x86]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7
            - name: Setup Ninja and CMake
              uses: lukka/get-cmake@latest
            - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
              uses: lukka/run-cmake@v10
              with:
                # This is the default path to the CMakeLists.txt along side the
                # CMakePresets.json. Change if you need have CMakeLists.txt and CMakePresets.json
                # located elsewhere.
                # cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'

                # You could use CMake workflow presets defined in the CMakePresets.json
                # with just this line below. Note this one cannot be used with any other
                # preset input, it is mutually exclusive.
                # workflowPreset: 'workflow-name'

                # This is the name of the CMakePresets.json's configuration to use to generate
                # the project files. This configuration leverages the vcpkg.cmake toolchain file to
                # run vcpkg and install all dependencies specified in vcpkg.json.
                configurePreset: 'ninja-multi-vcpkg'
                # Additional arguments can be appended to the cmake command.
                # This is useful to reduce the number of CMake's Presets since you can reuse
                # an existing preset with different variables.
                configurePresetAdditionalArgs: "['-DENABLE_YOUR_FEATURE=1']"

                # This is the name of the CMakePresets.json's configuration to build the project.
                buildPreset: 'ninja-multi-vcpkg'
                # Additional arguments can be appended when building, for example to specify the
                # configuration to build.
                # This is useful to reduce the number of CMake's Presets you need in CMakePresets.json.
                buildPresetAdditionalArgs: "['--config Release']"

                # This is the name of the CMakePresets.json's configuration to test the project with.
                testPreset: 'ninja-multi-vcpkg'
                # Additional arguments can be appended when testing, for example to specify the config
                # to test.
                # This is useful to reduce the number of CMake's Presets you need in CMakePresets.json.
                testPresetAdditionalArgs: "['--config Release']"